name: Build Feature
on:
  push: 
    branches:
    - feature/*
    - feature/**
    
jobs:
  build-feature:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: pull and checkout from git repository
        run: |
          echo "Pulling and checking out from git repository"

      - name: setup java
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - run: java HelloWorldApp.java

      - name: build with maven
        run: |
          mvnw clean install
          echo "proceso correcto"